session:
  store: "${SESSION_STORE:redis}"   # redis 또는 dynamodb

spring:
  redis:
    host: 10.30.0.14
    port: 6379

aws:
  dynamodb:
    region: "ap-northeast-2"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
metrics:
  export:
    prometheus:
      enabled: true